# .github/workflows/docker-multiarch.yml
name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU and Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: |
            linux/amd64,
            linux/arm64,
            linux/arm/v7,
            linux/arm/v6,
            linux/ppc64le,
            linux/s390x,
            linux/riscv64
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
